name: CI

on:
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 2 2 */4 *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    name: Build
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          cache: 'yarn'
      - run: yarn install
      - run: yarn run ci
